# Site settings
title: Nanotoolworks
email: X@3venn.com
description: Explain the intersection between three groups
twitter_username: 3venn
github_username:  3venn

# Build settings
markdown: kramdown
